sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm i -g npm@^4.0.0
before_script:
  - npm prune
  - npm run build
after_success:
  - npm run-script deploy
branches:
  only:
  - master
  - /^greenkeeper/.*$/
